[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "bst"
version = "1.0.0"
description = "Beat-Synchronous Tokenization for ECG Transformers"
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE" }
authors = [
    { name = "Ahmed Sameh" },
    { name = "Nolan Wilson" },
    { name = "Max Enderlein" },
    { name = "Yogatheesan Varatharajah" },
]

[tool.setuptools.packages.find]
include = ["bst*"]
